graph TD
    c1(Cloud Desktop Container 1)
    c2(Cloud Desktop Container 2)
    c3(Cloud Desktop Container 3)
    cluster(Cloud Desktop Cluster)

    c1 --- cluster
    c2 --- cluster
    c3 --- cluster
