graph TB
    tb3-ros(cosi119/tb3-ros)
    ubuntu-desktop-lxde-vnc(cosi119/ubuntu-desktop-lxde-vnc)
    ubuntu(ubuntu:18.04)
    ubuntu-cuda(nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu18.04)

    tb3-ros --- ubuntu-desktop-lxde-vnc ---|18.04| ubuntu
    ubuntu-desktop-lxde-vnc ---|18.04-cuda| ubuntu-cuda
