graph LR
    create-user(Create User)
    create-template(Create deployment files from template)
    create-dns-record(Create DNS record on AWS Route53)
    deploy-storage(Deploy storage on K8s)
    deploy-desktop(Deploy cloud desktop)
    
    subgraph au [add-user]
    create-user --> create-template
    end
    create-template --> create-dns-record
    subgraph anu [apply-new-user]
    create-dns-record --> deploy-storage
    deploy-storage --> deploy-desktop
    end
